"""create_phase2_tables

Revision ID: f5cf49589157
Revises: 001_create_phase1_tables
Create Date: 2026-02-20 07:16:58.297716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cf49589157'
down_revision: Union[str, Sequence[str], None] = '001_create_phase1_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_table('loan_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amortization_type', sa.String(length=50), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=50), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('grace_period_months', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_code'], ['gl_accounts.code'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_code'), 'journal_lines', ['account_code'], unique=False)
    op.create_index(op.f('ix_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('term_months', sa.BigInteger(), nullable=False),
    sa.Column('approved_principal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_customer_id'), 'loan_applications', ['customer_id'], unique=False)
    op.create_table('amortization_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('installment_number', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('penalty_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amortization_schedules_loan_id'), 'amortization_schedules', ['loan_id'], unique=False)
    op.create_table('loan_collateral',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_collateral_loan_id'), 'loan_collateral', ['loan_id'], unique=False)
    op.create_table('loan_guarantors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_guarantors_customer_id'), 'loan_guarantors', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loan_guarantors_loan_id'), 'loan_guarantors', ['loan_id'], unique=False)
    op.create_table('loan_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_loan_transactions_loan_id'), 'loan_transactions', ['loan_id'], unique=False)
    op.create_index(op.f('ix_customer_activities_created_at'), 'customer_activities', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_activities_created_at'), table_name='customer_activities')
    op.drop_index(op.f('ix_loan_transactions_loan_id'), table_name='loan_transactions')
    op.drop_table('loan_transactions')
    op.drop_index(op.f('ix_loan_guarantors_loan_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_customer_id'), table_name='loan_guarantors')
    op.drop_table('loan_guarantors')
    op.drop_index(op.f('ix_loan_collateral_loan_id'), table_name='loan_collateral')
    op.drop_table('loan_collateral')
    op.drop_index(op.f('ix_amortization_schedules_loan_id'), table_name='amortization_schedules')
    op.drop_table('amortization_schedules')
    op.drop_index(op.f('ix_loan_applications_customer_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_journal_lines_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_code'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_table('loan_products')
    op.drop_table('journal_entries')
    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
