import { useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { useQuery } from '@apollo/client'
import { GET_LOAN, GET_LOAN_AMORTIZATION } from '@/api/queries'
import { formatCurrency, formatDate } from '@/lib/utils'
import { Calculator, Loader2, ArrowLeft, Printer } from 'lucide-react'

interface LoanDetail {
    id: string
    customerId: string
    productId: string
    principal: number
    termMonths: number
    approvedPrincipal?: number
    approvedRate?: number
    status: string
    createdAt: string
    disbursedAt?: string
    borrowerName: string
    productName: string
}

interface AmortizationRow {
    installmentNumber: number
    dueDate: string
    principalDue: number
    interestDue: number
    penaltyDue: number
    principalPaid: number
    interestPaid: number
    penaltyPaid: number
    status: string
    totalDue: number
    totalPaid: number
}

export default function AmortizationSchedulePage() {
    const { id } = useParams<{ id: string }>()
    const [showAll, setShowAll] = useState(false)

    const { data: loanData, loading: loanLoading, error: loanError } = useQuery(GET_LOAN, {
        variables: { id },
        skip: !id
    })

    const { data: amortizationData, loading: amortizationLoading, error: amortizationError } = useQuery(GET_LOAN_AMORTIZATION, {
        variables: { loanId: id ? parseInt(id) : 0 },
        skip: !id || isNaN(parseInt(id))
    })

    const loan: LoanDetail = loanData?.loan?.loan
    const amortizationRows: AmortizationRow[] = amortizationData?.loanAmortization?.rows || []

    const principal = parseFloat(String(loan?.approvedPrincipal || loan?.principal || 0))
    const annualRatePercent = parseFloat(String(loan?.approvedRate || 0))
    const termMonths = parseInt(String(loan?.termMonths || 0))

    const totalInterest = amortizationRows.reduce((sum, row) => sum + (row.interestDue || 0), 0)
    const totalPayments = principal + totalInterest
    const periodicPayment = termMonths > 0 ? totalPayments / termMonths : 0

    const displayRows = showAll ? amortizationRows : amortizationRows.slice(0, 12)

    const handlePrint = () => {
        window.print()
    }

    if (loanLoading || amortizationLoading) {
        return (
            <div className="flex items-center justify-center h-64">
                <Loader2 className="w-6 h-6 animate-spin text-yellow-400" />
            </div>
        )
    }

    if (loanError) {
        return (
            <div className="p-10 text-center text-destructive">
                Error loading loan: {loanError.message}
            </div>
        )
    }

    if (!loan) {
        return (
            <div className="p-10 text-center text-muted-foreground">
                Loan not found. <Link to="/loans" className="text-primary hover:underline">Go to Loans</Link>
            </div>
        )
    }

    return (
        <div className="space-y-6 animate-fade-in">
            {/* Header */}
            <div className="flex items-center justify-between no-print">
                <div className="flex items-center gap-4">
                    <Link
                        to={`/loans/${id}`}
                        className="p-2 hover:bg-secondary rounded-lg transition-colors"
                    >
                        <ArrowLeft className="w-5 h-5" />
                    </Link>
                    <div>
                        <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
                            <Calculator className="w-6 h-6 text-yellow-400" /> Amortization Schedule
                        </h1>
                        <p className="text-muted-foreground text-sm mt-1">
                            Loan ID: ...{loan.id?.slice(-6)} | {loan.borrowerName || 'N/A'}
                        </p>
                    </div>
                </div>
                <button
                    onClick={handlePrint}
                    className="flex items-center gap-2 px-4 py-2 bg-secondary border border-border rounded-lg text-sm hover:bg-secondary/80 transition-colors"
                >
                    <Printer className="w-4 h-4" />
                    Print
                </button>
            </div>

            {/* Loan Summary */}
            <div className="glass p-6 rounded-xl">
                <div className="flex justify-between items-start mb-6 border-b border-border/50 pb-4">
                    <div>
                        <h2 className="text-xl font-bold text-gray-800">Loan Amortization Schedule</h2>
                        <p className="text-blue-600 text-sm mt-1">Generated by LendingMVP System</p>
                    </div>
                    <div className="text-right">
                        <div className="flex items-center justify-end">
                            <span className="text-xl font-bold text-gray-700">Lending<span className="text-blue-500 italic">MVP</span></span>
                        </div>
                        <p className="text-xs text-gray-400 mt-1">© 2026 IJE Software LLC</p>
                    </div>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-6">
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Principal</p>
                        <p className="text-lg font-bold mt-1">{formatCurrency(principal)}</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Interest Rate</p>
                        <p className="text-lg font-bold mt-1">{annualRatePercent}%</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Term</p>
                        <p className="text-lg font-bold mt-1">{termMonths} months</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Disbursement Date</p>
                        <p className="text-lg font-bold mt-1">{loan.disbursedAt ? formatDate(loan.disbursedAt) : formatDate(loan.createdAt)}</p>
                    </div>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-6 pt-4 border-t border-border/50">
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Payment Frequency</p>
                        <p className="text-lg font-bold mt-1">Monthly</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Periodic Rate</p>
                        <p className="text-lg font-bold mt-1">{(annualRatePercent / 12).toFixed(3)}%</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Total Interest</p>
                        <p className="text-lg font-bold mt-1">{formatCurrency(totalInterest)}</p>
                    </div>
                    <div>
                        <p className="text-xs text-muted-foreground uppercase tracking-wider">Total Payments</p>
                        <p className="text-lg font-bold mt-1">{formatCurrency(totalPayments)}</p>
                    </div>
                </div>
            </div>

            {/* Periodic Payment Summary */}
            <div className="glass p-6 rounded-xl">
                <p className="text-xs text-muted-foreground uppercase tracking-wider mb-2">Monthly Payment</p>
                <p className="text-3xl font-bold text-gray-900">{formatCurrency(periodicPayment)}</p>
            </div>

            {/* Amortization Table */}
            <div className="glass rounded-xl overflow-hidden">
                <table className="w-full text-sm">
                    <thead className="bg-secondary/40">
                        <tr>
                            <th className="px-3 py-3 text-center font-semibold text-muted-foreground">No.</th>
                            <th className="px-3 py-3 text-left font-semibold text-muted-foreground">Due Date</th>
                            <th className="px-3 py-3 text-right font-semibold text-muted-foreground">Payment</th>
                            <th className="px-3 py-3 text-right font-semibold text-muted-foreground">Principal</th>
                            <th className="px-3 py-3 text-right font-semibold text-muted-foreground">Interest</th>
                            <th className="px-3 py-3 text-right font-semibold text-muted-foreground">Total</th>
                            <th className="px-3 py-3 text-right font-semibold text-muted-foreground">Balance</th>
                        </tr>
                    </thead>
                    <tbody>
                        {/* Initial Balance Row */}
                        <tr className="border-b border-gray-300 bg-gray-50">
                            <td className="px-3 py-2 text-center text-gray-500">-</td>
                            <td className="px-3 py-2 text-gray-500">Starting Balance</td>
                            <td className="px-3 py-2 text-right text-gray-500">-</td>
                            <td className="px-3 py-2 text-right text-gray-500">-</td>
                            <td className="px-3 py-2 text-right text-gray-500">-</td>
                            <td className="px-3 py-2 text-right text-gray-500">-</td>
                            <td className="px-3 py-2 text-right font-medium border border-gray-300 bg-white">
                                {formatCurrency(principal)}
                            </td>
                        </tr>
                        {displayRows.map((row, index) => {
                            const prevBalance = index === 0 ? principal : displayRows[index - 1].principalDue - displayRows[index - 1].principalPaid + (displayRows[index - 1].interestDue - displayRows[index - 1].interestPaid)
                            const balance = prevBalance - (row.principalDue - row.principalPaid)
                            return (
                                <tr key={row.installmentNumber} className="border-b border-gray-200 hover:bg-gray-50">
                                    <td className="px-3 py-2 text-center text-gray-600">{row.installmentNumber}</td>
                                    <td className="px-3 py-2 text-center">{formatDate(row.dueDate)}</td>
                                    <td className="px-3 py-2 text-right">{formatCurrency(row.totalDue)}</td>
                                    <td className="px-3 py-2 text-right">{formatCurrency(row.principalDue)}</td>
                                    <td className="px-3 py-2 text-right">{formatCurrency(row.interestDue)}</td>
                                    <td className="px-3 py-2 text-right font-medium">{formatCurrency(row.totalDue)}</td>
                                    <td className="px-3 py-2 text-right border border-gray-300 bg-white">
                                        {balance > 0.01 ? formatCurrency(balance) : '0.00'}
                                    </td>
                                </tr>
                            )
                        })}
                    </tbody>
                </table>
            </div>

            {/* Show More / Less */}
            {amortizationRows.length > 12 && (
                <div className="text-center no-print">
                    <button
                        onClick={() => setShowAll(!showAll)}
                        className="px-6 py-2 bg-secondary border border-border rounded-lg text-sm hover:bg-secondary/80 transition-colors"
                    >
                        {showAll ? 'Show Less' : `Show All (${amortizationRows.length} payments)`}
                    </button>
                </div>
            )}

            {/* Error Message */}
            {amortizationError && (
                <div className="glass p-4 rounded-xl border border-yellow-500/30 bg-yellow-500/10">
                    <p className="text-yellow-400 text-sm">
                        Could not load amortization schedule from server. Showing calculated values instead.
                    </p>
                </div>
            )}
        </div>
    )
}
